FROM postgres:latest
USER 0
RUN apt-get update
RUN apt-get install -y tcpdump
RUN apt-get install -y nmap

#RUN tcpdump -i eth0
#RUN apt update && apt-get install -y tcpdump && apt-get install -y nmap && tcpdump -i eth0
#RUN apt-get update && apt-get install -y tcpdump && apt-get install -y nmap && tcpdump -i eth0
#RUN microdnf update && microdnf install -y tcpdump && microdnf install -y nmap && tcpdump -i eth0