version: '3'
services:
  postgres:
    #image: postgres:latest
    container_name: postgres
    build:
      context: ./
      dockerfile: Dockerfile     
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: qDxNr!LwjgHh6&B5mkK^a
    networks:
    - my-custom-network
    
networks:
  my-custom-network:
    external: true     