version: '3:8'
services:
  mongodb:
    #image: mongo:5.0.6-focal
    container_name: mongodb
    build:
      context: ./
      dockerfile: DockerfileMongo    
    #restart: always
    ports:
    - "27017:27017"
    # volume no esta definido
    #volumes:
    #- ~/Desktop/node-mongo-rest-api/data:/data/db
    networks:
    - my-custom-network
       
      
  mongo-express:
    #image: mongo-express:1.0.0-alpha.4
    container_name: mongoui
    build:
      context: ./
      dockerfile: DockerfileMongo-express   
    #restart: always
    ports:
    - "8080:8081"
    depends_on:
    - mongodb
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: qDxNr!LwjgHh6&B5mkK^a
    #links:
    #- mongodb
    networks:
    - my-custom-network
    
networks:
  my-custom-network:
    external: true     
        
#networks:
#    mongo-network:
#        driver: bridge
 