version: '3'
services:
  oracle-xe:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-xe
    #build:
    #  context: ./
    #  dockerfile: Dockerfile      
    ports:
    - "1521:1521"
    environment:
      ORACLE_PASSWORD: qDxNr!LwjgHh6B5mkKa
    networks:
    - my-custom-network
    
networks:
  my-custom-network:
    external: true     