version: '3'
services:
  mssql:
    #image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    build:
      context: ./
      dockerfile: Dockerfile     
    ports:
    - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: qDxNr!LwjgHh6&B5mkK^a
    networks:
    - my-custom-network
    
networks:
  my-custom-network:
    external: true 