FROM mysql:latest
RUN microdnf update
RUN microdnf install -y tcpdump
RUN microdnf install -y nmap
#RUN tcpdump -i eth0

#RUN apt-get update && apt-get install -y tcpdump && apt-get install -y nmap && tcpdump -i eth0
#RUN microdnf update && microdnf install -y tcpdump && microdnf install -y nmap && tcpdump -i eth0