version: "3.8"
services:
  mysql:
    #image: mysql:latest
    container_name: mysql
    build:
      context: ./
      dockerfile: Dockerfile    
    ports:
    - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: qDxNr!LwjgHh6&B5mkK^a
    networks:
    - my-custom-network
    
networks:
  my-custom-network:
    external: true 